[2022-10-04 19:07:54,738] logging_util.py->error_log line:64 [INFO]读取yaml测试用例报错：异常信息：Traceback (most recent call last):
  File "C:\pycharm\common\parameters_util.py", line 61, in read_testcase_file
    with open(get_object_path() + yaml_path, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\pycharm/testcases/gzh/get_token.yml'

